// Copyright 2024-2026 The Greeting Inc. All rights reserved.
// Use of this source code is governed by a BSD-style license.

import Barnard
import BarnardCore
import BeidSharedKit
import XCTest
@testable import Beid

/// Coverage for `ProductionVenueBundleVerifier` (beid#432) and the pure
/// `VenueBundleVerificationLogic` helpers it is built from.
///
/// The identity chain (`verifyVenueBundleIdentity` via `RegistryClient`)
/// cannot be exercised offline: `RegistryResolution`/`VenueBundleIdentity`
/// have Kotlin-`internal` constructors, so Swift can construct neither a
/// fake registry answer nor a fake identity, and `RegistryClient` itself has
/// no test-injectable transport reachable from Swift. Every existing
/// production registry consumer in `ios/Beid` (`RegistryEventIdentityVerificationSource`,
/// `RegistryEventJoinRegistry`) has the same limit. What IS tested here,
/// without a network, is real: the B005 signature/window/agreement logic
/// (using barnard's own real-signed producer fixture), every pure mapping
/// and arithmetic helper, and the two wiring paths that are genuinely
/// reachable offline (malformed bytes, unconfigured registry client).
@MainActor
final class ProductionVenueBundleVerifierTests: XCTestCase {

  // MARK: - Real signed envelope fixture

  /// `container_hex`/`current_enin` from barnard's
  /// `test-vectors/venue-envelope-producer-fixture.txt`, generated by
  /// `VenueEnvelopeProducerTests.testWriteCrossLanguageFixture` against a
  /// REAL signing key and `BarnardCoreSigning.signRecoverable` -- not a
  /// hand-written vector. Verified independently against these bytes in this
  /// PR: registrar/anchor/nonce are 0xa1/0xa2/0xa3 repeated, one authority
  /// key, joinMode 0, eninSeconds 300, validFromEnin 6,000,000,
  /// validThroughEnin 6,000,010, relayExpiresAtEnin 6,000,004, display name
  /// "Venue Test Event", no delegation cert.
  private static let realContainerHex =
    "030000d601a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2" +
    "a2a2a2a2a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3010279be667e" +
    "f9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179800012c005b8d80005b8d8a005b8" +
    "d8402236c422fa9e53e281056656e75652054657374204576656e74000f02ac07c182b379723813bf05" +
    "46ce0991cc0d05022c49dd1c7068a2f22a0ffb29ad1ee643185f0f260459c2808aae5a1c871784bd93ff" +
    "4d8bc8b87f634596fe00"
  private static let realContainerCurrentEnin: Int64 = 6_000_001

  private static func realContainer() throws -> [UInt8] {
    try hexBytes(realContainerHex)
  }

  private static func hexBytes(_ hex: String) throws -> [UInt8] {
    var result: [UInt8] = []
    result.reserveCapacity(hex.count / 2)
    var index = hex.startIndex
    while index < hex.endIndex {
      let next = hex.index(index, offsetBy: 2)
      result.append(try XCTUnwrap(UInt8(hex[index..<next], radix: 16)))
      index = next
    }
    return result
  }

  private let nameValidator = BarnardB005NativeDisplayNameNormalizer()

  // MARK: - Real B005 verification (production Barnard code, no shared/ involved)

  func testRealSignedEnvelopeVerifiesAtItsOwnCurrentEnin() throws {
    let container = try Self.realContainer()
    let verified = BarnardB005EnvelopeV2.verify(
      container: container, currentEnin: Self.realContainerCurrentEnin, nameValidator: nameValidator
    )
    let unwrapped = try XCTUnwrap(verified)
    XCTAssertEqual(unwrapped.validFromEnin, 6_000_000)
    XCTAssertEqual(unwrapped.relayExpiresAtEnin, 6_000_004)
    XCTAssertEqual(unwrapped.validThroughEnin, 6_000_010)
    XCTAssertEqual(unwrapped.eninSeconds, 300)
    XCTAssertEqual(unwrapped.eventDisplayName, "Venue Test Event")
    XCTAssertEqual(unwrapped.joinMode, 0)
  }

  /// Negative control: a mutated signature byte fails verification. This
  /// exercises pre-existing Barnard code, not code this PR adds; it is
  /// evidence for the verifier's reliance on `verify`, not a fail-then-pass
  /// test of new behavior.
  func testMutatedSignatureByteFailsVerification() throws {
    var container = try Self.realContainer()
    container[container.count - 1] ^= 0x01
    XCTAssertNil(
      BarnardB005EnvelopeV2.verify(
        container: container, currentEnin: Self.realContainerCurrentEnin, nameValidator: nameValidator
      )
    )
  }

  /// The terminal-ENIN constraint from the brief: `relayExpiresAtEnin` is
  /// EXCLUSIVE, so `currentEnin == relayExpiresAtEnin` must not verify.
  func testEnvelopeIsNotServableAtItsOwnRelayExpiryEnin() throws {
    let container = try Self.realContainer()
    XCTAssertNil(
      BarnardB005EnvelopeV2.verify(container: container, currentEnin: 6_000_004, nameValidator: nameValidator)
    )
    // One ENIN earlier is still inside the half-open window.
    XCTAssertNotNil(
      BarnardB005EnvelopeV2.verify(container: container, currentEnin: 6_000_003, nameValidator: nameValidator)
    )
  }

  // MARK: - registryAgreement (real crypto, hand-constructed definition -- no chain read)

  private func verifiedFixtureEnvelope() throws -> BarnardB005VerifiedEnvelope {
    try XCTUnwrap(BarnardB005EnvelopeV2.verify(
      container: Self.realContainer(), currentEnin: Self.realContainerCurrentEnin, nameValidator: nameValidator
    ))
  }

  func testRegistryAgreementAgreesWhenTheDefinitionContainsTheEnvelopesWindow() throws {
    let verified = try verifiedFixtureEnvelope()
    let definition = BarnardEventDefinitionV1(
      eventId: verified.eventId,
      keySetDigest: verified.keySetDigest,
      joinMode: verified.joinMode,
      eventCodeHash: verified.eventCodeHash,
      // [5,999,990, 6,000,010] at 300s/ENIN, matching the registry-side ENIN
      // conversion in BarnardB005EnvelopeV2.registryAgreement's own doc.
      validFromUnixSeconds: 1_799_997_000,
      validUntilUnixSeconds: 1_800_003_299
    )
    XCTAssertEqual(BarnardB005EnvelopeV2.registryAgreement(verified, definition: definition), .agrees)
  }

  func testRegistryAgreementMismatchesOnAForeignEventId() throws {
    let verified = try verifiedFixtureEnvelope()
    var foreignEventId = verified.eventId
    foreignEventId[0] ^= 0x01
    let definition = BarnardEventDefinitionV1(
      eventId: foreignEventId,
      keySetDigest: verified.keySetDigest,
      joinMode: verified.joinMode,
      eventCodeHash: verified.eventCodeHash,
      validFromUnixSeconds: 1_799_997_000,
      validUntilUnixSeconds: 1_800_003_299
    )
    guard case .mismatched(let fields) = BarnardB005EnvelopeV2.registryAgreement(verified, definition: definition)
    else { return XCTFail("expected a mismatch") }
    XCTAssertTrue(fields.contains(.EVENT_ID))
  }

  // MARK: - VenueBundleVerificationLogic: import failure code mapping

  func testImportFailureMapsEveryKnownIdentityCode() {
    let table: [(String, VenueImportFailure)] = [
      ("handoff_mismatch", .handoffMismatch),
      ("deployment_mismatch", .unsupportedDeployment),
      ("registry_unavailable", .registryUnavailable),
      ("registry_source_mismatch", .registrySourceMismatch),
      ("definition_not_registered", .anchoredRecordMissing),
      ("invalid_definition", .definitionRejected),
    ]
    for (code, expected) in table {
      XCTAssertEqual(VenueBundleVerificationLogic.importFailure(forIdentityCode: code), expected, code)
    }
  }

  func testImportFailureFailsClosedOnAnUnknownCode() {
    XCTAssertNil(VenueBundleVerificationLogic.importFailure(forIdentityCode: "some_future_code"))
  }

  // MARK: - VenueBundleVerificationLogic: serving block code mapping

  func testServingBlockIsAVerbatimRawValueLookupForEveryCase() {
    for reason in VenueServingBlock.allCases {
      XCTAssertEqual(VenueBundleVerificationLogic.servingBlock(forCode: reason.rawValue), reason)
    }
  }

  func testServingBlockFailsClosedOnAnUnknownCode() {
    XCTAssertNil(VenueBundleVerificationLogic.servingBlock(forCode: "someFutureBlockCode"))
  }

  // MARK: - VenueBundleVerificationLogic: join mode

  func testBarnardJoinModeMapsOpenAndGatedAndFailsClosedOnNil() {
    XCTAssertEqual(
      VenueBundleVerificationLogic.barnardJoinMode(
        ExportedKotlinPackages.org.levarac.parallax.registry.EventJoinMode.OPEN
      ), 0
    )
    XCTAssertEqual(
      VenueBundleVerificationLogic.barnardJoinMode(
        ExportedKotlinPackages.org.levarac.parallax.registry.EventJoinMode.GATED
      ), 1
    )
    XCTAssertNil(VenueBundleVerificationLogic.barnardJoinMode(nil))
  }

  // MARK: - VenueBundleVerificationLogic: definition projection

  /// `shared/`'s gated verdict maps to the native case that refuses to serve.
  ///
  /// The DECISION this used to make now lives in `shared/`
  /// (`classifyVenueDefinition`), exercised against real codec output by
  /// `VenueDefinitionClassificationTest`, which is where the "a gated
  /// definition carries no eventCodeHash" reasoning and the 8-byte check are
  /// now asserted. What is left on this side is the mapping, and that is what
  /// this tests. Reverting `definitionProjection(for:)`'s body to `.unusable`
  /// for every input turns this RED; see the PR body for the captured output.
  func testSharedGatedVerdictMapsToTheNativeRefusal() {
    XCTAssertEqual(
      VenueBundleVerificationLogic.definitionProjection(
        for: ExportedKotlinPackages.org.levarac.parallax.venue
          .VenueDefinitionClassification.GATED_REQUIRES_EXTERNAL_HASH
      ),
      .gatedUnsupported
    )
  }

  /// Every `shared/` verdict maps to exactly one native case, and no two
  /// collapse together. A mapping that sent two verdicts to the same native
  /// case would make a gated pack indistinguishable from a malformed one
  /// again, which is the defect this whole chain exists to prevent.
  func testEverySharedVerdictMapsToItsOwnNativeCase() {
    typealias Classification =
      ExportedKotlinPackages.org.levarac.parallax.venue.VenueDefinitionClassification
    let table: [(Classification, VenueBundleVerificationLogic.DefinitionProjection)] = [
      (.OPEN_WITH_EVENT_CODE_HASH, .open),
      (.GATED_REQUIRES_EXTERNAL_HASH, .gatedUnsupported),
      (.NO_USABLE_JOIN_DECLARATION, .unusable),
    ]
    for (verdict, expected) in table {
      XCTAssertEqual(VenueBundleVerificationLogic.definitionProjection(for: verdict), expected)
    }
    XCTAssertEqual(Set(table.map(\.1)).count, table.count, "two shared verdicts must not share one native case")
    // The table above is hand-written, so on its own it can only check the
    // cases it already mentions -- a case added in `shared/` would simply go
    // unlisted, and nothing else would catch it: Swift Export renders the
    // Kotlin enum as a class, so the compiler cannot demand exhaustiveness
    // either (see `definitionProjection(for:)`). Binding a future Android
    // consumer to the SAME decision is why this classification lives in
    // `shared/` at all, so an unnoticed divergence here would cost exactly
    // the guarantee the move was made to buy. The generated class conforms to
    // `CaseIterable`, so the type can be asked directly.
    XCTAssertEqual(
      Classification.allCases.count,
      table.count,
      "shared/ declares \(Classification.allCases.count) VenueDefinitionClassification cases but this native "
        + "mapping table covers \(table.count). Add the missing case to the table and to "
        + "VenueBundleVerificationLogic.definitionProjection(for:)."
    )
  }

  /// Import refuses a gated definition, with its own outcome.
  ///
  /// Before this, nothing was decided about join mode at import: every
  /// definition that verified was imported, and a gated one then failed at
  /// serving time as `envelopeRejected` -- a verdict about an envelope that
  /// had verified fine. Reverting `importFailure(forProjection:)` to that
  /// previous behaviour (`return nil` for every projection, i.e. import never
  /// decides on join mode) turns this RED; see the PR body for the captured
  /// output.
  func testImportRefusesAGatedDefinitionWithItsOwnOutcome() {
    XCTAssertEqual(
      VenueBundleVerificationLogic.importFailure(forProjection: .gatedUnsupported),
      .gatedEventUnsupported
    )
  }

  /// Import decides ONLY the gated case. An open event imports, and a
  /// definition that will not project for some other reason keeps the path it
  /// has always had -- refused at serving time, not relocated to import.
  func testImportDecidesOnlyTheGatedCaseAndRelocatesNoOtherRefusal() {
    XCTAssertNil(VenueBundleVerificationLogic.importFailure(forProjection: .open))
    XCTAssertNil(VenueBundleVerificationLogic.importFailure(forProjection: .unusable))
  }

  // MARK: - VenueBundleVerificationLogic: ENIN window arithmetic

  func testDefinitionEninWindowMatchesTheKnownFixtureConversion() {
    // shared/'s venue-current-lease-v1.json fixture: validFrom 1,799,997,000,
    // validUntil 1,800,003,299, eninSeconds 300 -> [5,999,990, 6,000,010].
    // Cross-checked independently in Python against
    // BarnardB005EnvelopeV2.registryAgreement's own formula before writing
    // this assertion.
    let window = VenueBundleVerificationLogic.definitionEninWindow(
      validFromUnixSeconds: 1_799_997_000, validUntilUnixSeconds: 1_800_003_299, eninSeconds: 300
    )
    XCTAssertEqual(window?.start, 5_999_990)
    XCTAssertEqual(window?.end, 6_000_010)
  }

  func testDefinitionEninWindowRejectsAMalformedWindow() {
    XCTAssertNil(VenueBundleVerificationLogic.definitionEninWindow(
      validFromUnixSeconds: 100, validUntilUnixSeconds: 50, eninSeconds: 300
    ))
    XCTAssertNil(VenueBundleVerificationLogic.definitionEninWindow(
      validFromUnixSeconds: 0, validUntilUnixSeconds: 100, eninSeconds: 0
    ))
    XCTAssertNil(VenueBundleVerificationLogic.definitionEninWindow(
      validFromUnixSeconds: -1, validUntilUnixSeconds: 100, eninSeconds: 300
    ))
  }

  func testFloorDivAndFloorModMatchKotlinSemanticsForNegativeInputs() {
    // Swift's native `/`/`%` truncate toward zero: -7 / 2 == -3, -7 % 2 ==
    // -1. Kotlin's floorDiv/floorMod round toward negative infinity:
    // floorDiv(-7, 2) == -4, floorMod(-7, 2) == 1. If this test used Swift's
    // operators directly it would assert the wrong numbers.
    XCTAssertEqual(VenueBundleVerificationLogic.floorDiv(-7, 2), -4)
    XCTAssertEqual(VenueBundleVerificationLogic.floorMod(-7, 2), 1)
    XCTAssertEqual(VenueBundleVerificationLogic.floorDiv(7, 2), 3)
    XCTAssertEqual(VenueBundleVerificationLogic.floorMod(7, 2), 1)
  }

  // MARK: - VenueBundleVerificationLogic: coverage-gap detection

  func testCoverageGapDetectsAMissingFutureSlice() {
    // Exactly the real producer fixture's situation: one envelope covering
    // only [6,000,000, 6,000,004) inside a wider required span.
    XCTAssertTrue(VenueBundleVerificationLogic.hasCoverageGap(
      candidates: [(6_000_000, 6_000_004)], requiredStart: 5_999_990, requiredEnd: 6_000_010
    ))
  }

  func testCoverageGapIsFalseWhenIntervalsExactlyTileTheRequiredSpan() {
    XCTAssertFalse(VenueBundleVerificationLogic.hasCoverageGap(
      candidates: [(5_999_990, 6_000_000), (6_000_000, 6_000_004), (6_000_004, 6_000_010)],
      requiredStart: 5_999_990, requiredEnd: 6_000_010
    ))
  }

  func testCoverageGapToleratesOverlapButNotAGap() {
    XCTAssertFalse(VenueBundleVerificationLogic.hasCoverageGap(
      candidates: [(5_999_990, 6_000_005), (6_000_003, 6_000_010)],
      requiredStart: 5_999_990, requiredEnd: 6_000_010
    ))
    XCTAssertTrue(VenueBundleVerificationLogic.hasCoverageGap(
      candidates: [(5_999_990, 6_000_003), (6_000_004, 6_000_010)],
      requiredStart: 5_999_990, requiredEnd: 6_000_010
    ))
  }

  func testCoverageGapNeverRequiresTheExclusiveTerminalEnin() {
    // requiredEnd itself (the definition's own inclusive last ENIN, +1) can
    // never be covered by construction (relayExpiresAtEnin <= validThroughEnin),
    // so a single envelope reaching exactly requiredEnd must be sufficient.
    XCTAssertFalse(VenueBundleVerificationLogic.hasCoverageGap(
      candidates: [(5_999_990, 6_000_010)], requiredStart: 5_999_990, requiredEnd: 6_000_010
    ))
  }

  // MARK: - coverageOutcome: fail closed, never a pass-through, when coverage is uncomputable

  /// "Could not determine coverage" must never read as "coverage is
  /// satisfied." Reverting `coverageOutcome` to the `if let ... else fall
  /// through to .covered` shape it replaced turns this RED: see the PR body
  /// for the captured output.
  func testCoverageOutcomeRefusesRatherThanPassingThroughWhenNothingVerified() {
    XCTAssertEqual(
      VenueBundleVerificationLogic.coverageOutcome(
        referenceEninSeconds: nil, validFromUnixSeconds: 0, validUntilUnixSeconds: 100, coverageIntervals: []
      ),
      .uncomputable
    )
  }

  func testCoverageOutcomeRefusesRatherThanPassingThroughWhenTheDefinitionWindowIsMalformed() {
    // validFrom > validUntil, despite a reference eninSeconds being
    // available from some verified envelope -- this must refuse, not fall
    // through as though coverage were satisfied.
    XCTAssertEqual(
      VenueBundleVerificationLogic.coverageOutcome(
        referenceEninSeconds: 300, validFromUnixSeconds: 100, validUntilUnixSeconds: 0, coverageIntervals: []
      ),
      .uncomputable
    )
  }

  func testCoverageOutcomeDistinguishesAGapFromFullCoverage() {
    XCTAssertEqual(
      VenueBundleVerificationLogic.coverageOutcome(
        referenceEninSeconds: 300, validFromUnixSeconds: 1_799_997_000, validUntilUnixSeconds: 1_800_003_299,
        coverageIntervals: [(6_000_000, 6_000_004)]
      ),
      .gap
    )
    XCTAssertEqual(
      VenueBundleVerificationLogic.coverageOutcome(
        referenceEninSeconds: 300, validFromUnixSeconds: 1_799_997_000, validUntilUnixSeconds: 1_800_003_299,
        coverageIntervals: [(5_999_990, 6_000_010)]
      ),
      .covered
    )
  }

  // MARK: - Phase-1 scope: why the coverage gate is not wired to a refusal

  /// The phase-1 scope claim, stated over the real producer fixture.
  ///
  /// This test passes both before and after the coverage gate was unwired,
  /// and is recorded as such rather than offered as fail-then-pass evidence:
  /// it asserts facts about the fixture, not about the call site. The call
  /// site itself is unreachable offline for the reason this class's header
  /// already gives -- `VenueBundleIdentity` (`VenueBundleIdentity.kt:17`) and
  /// `EventDefinition` (`EventDefinitionModels.kt:70`) both have Kotlin
  /// `internal` constructors, so Swift can construct neither input
  /// `evaluateCurrentLease` takes.
  ///
  /// What it does pin down is why the gate had to go. The single envelope
  /// barnard's producer actually emits IS servable at a current ENIN inside
  /// its own window, and the same envelope CANNOT tile the definition's whole
  /// validity window. Under the removed gate those two facts together refused
  /// the pack before `evaluateVenueCurrentLease` could issue a current permit
  /// or a `notStarted` recheck. The venue lane owner's 2026-09-10 ruling in
  /// `docs/plans/2026-09-10-venue-bundle-import.md` puts whole-window
  /// coverage in phase 2.
  func testTheRealProducerFixtureIsServableNowYetCannotTileItsOwnDefinitionWindow() throws {
    let verified = try verifiedFixtureEnvelope()
    // Servable at a current ENIN inside its window. This is the phase-1
    // claim: a current lease after real SDK verification at that ENIN.
    XCTAssertNotNil(BarnardB005EnvelopeV2.verify(
      container: try Self.realContainer(),
      currentEnin: Self.realContainerCurrentEnin,
      nameValidator: nameValidator
    ))
    // The same envelope, measured against the shared fixture's definition
    // window, is a coverage gap -- computed from the VERIFIED bounds rather
    // than from hand-written numbers.
    XCTAssertEqual(
      VenueBundleVerificationLogic.coverageOutcome(
        referenceEninSeconds: verified.eninSeconds,
        validFromUnixSeconds: 1_799_997_000,
        validUntilUnixSeconds: 1_800_003_299,
        coverageIntervals: [(verified.validFromEnin, verified.relayExpiresAtEnin)]
      ),
      .gap
    )
  }

  // MARK: - Wiring: reachable offline without a chain

  func testMalformedBundleBytesAreRejectedWithoutTouchingTheRegistry() async {
    let verifier = ProductionVenueBundleVerifier(registryClient: nil)
    let result = await verifier.importBundle(bundleBytes: Data([0xff, 0x00]), handoffBytes: Data([0xff, 0x00]))
    guard case .rejected(let failure) = result else { return XCTFail("expected a rejection") }
    XCTAssertEqual(failure, .malformedOrOutOfBounds)
  }

  /// Uses the shared fixture's real, well-formed bundle/handoff CBOR bytes
  /// (decode only checks shape and digest agreement between the two, never
  /// chain state) so this exercises the "decode succeeded, no registry
  /// client to ask" branch specifically -- distinct from the malformed-bytes
  /// test above, which never reaches the registry step at all.
  func testNoConfiguredRegistryClientRejectsImportAsRegistryUnavailable() async throws {
    let fixture = try VenueServingContractFixture.load()
    let verifier = ProductionVenueBundleVerifier(registryClient: nil)
    let result = await verifier.importBundle(
      bundleBytes: fixture.artifact.bundleBytes, handoffBytes: fixture.artifact.handoffBytes
    )
    guard case .rejected(let failure) = result else { return XCTFail("expected a rejection") }
    XCTAssertEqual(failure, .registryUnavailable)
  }

  func testEvaluateWithNoRegistryClientBlocksAsRegistryUnavailable() async throws {
    let fixture = try VenueServingContractFixture.load()
    let verifier = ProductionVenueBundleVerifier(registryClient: nil)
    let decision = await verifier.evaluate(fixture.imported(), clock: .available(unixSeconds: 1_800_000_000))
    guard case .blocked(let rejection) = decision else { return XCTFail("expected a block") }
    XCTAssertEqual(rejection.reason, .registryUnavailable)
  }

  func testEvaluateWithUnavailableClockBlocksBeforeTouchingTheRegistry() async throws {
    let fixture = try VenueServingContractFixture.load()
    // No registry client configured at all: if evaluate() reached the
    // registry step despite the clock being unavailable, this would still
    // report registryUnavailable, not clockUnavailable -- so this also
    // proves clock-unavailability is checked FIRST.
    let verifier = ProductionVenueBundleVerifier(registryClient: nil)
    let decision = await verifier.evaluate(fixture.imported(), clock: .unavailable)
    guard case .blocked(let rejection) = decision else { return XCTFail("expected a block") }
    XCTAssertEqual(rejection.reason, .clockUnavailable)
  }

  /// This crosses the real iOS production composition path: the production
  /// RegistryClient resolves a recorded registry response through its Darwin
  /// HTTP transport, shared verifies the signed bundle identity, and the
  /// production verifier derives the current lease. No Kotlin object is
  /// constructed by Swift; the only test seam is URLProtocol at the HTTP
  /// boundary used by the existing production client.
  func testProductionClientAndVerifierReachPermittedForTheRealSignedFixture() async throws {
    let fixture = try VenueServingContractFixture.load()
    let server = try LoopbackJSONRPCServer { body in
      RecordedVenueRegistryURLProtocol.responseData(for: body)
    }
    let endpoint = try await server.start()
    defer { server.stop() }

    let client = try XCTUnwrap(
      ExportedKotlinPackages.org.levarac.parallax.registry.createSepoliaRegistryClientWithRpcEndpoints(
        readerAddressHex: "0xd4852f8526a1555a1b2c34145f0ecda412a53c51",
        primaryEndpointUrl: endpoint.absoluteString,
        secondaryEndpointUrl: endpoint.absoluteString
      )
    )
    defer { client.close() }
    let verifier = ProductionVenueBundleVerifier(registryClient: client)

    let importedResult = await verifier.importBundle(
      bundleBytes: fixture.artifact.bundleBytes,
      handoffBytes: fixture.artifact.handoffBytes
    )
    guard case .imported(let imported) = importedResult else {
      return XCTFail("the production client and signed fixture must reach imported, got \(importedResult); server=\(server.summary)")
    }

    let decision = await verifier.evaluate(
      imported,
      clock: .available(unixSeconds: VenueServingContractFixture.currentUnixSeconds)
    )
    guard case .permitted(let permit) = decision else {
      return XCTFail("the production verifier must reach permitted, got \(decision)")
    }
    XCTAssertEqual(permit.identity.eventIdHex, VenueServingContractFixture.eventIdHex)
    XCTAssertGreaterThan(permit.stopAtUnixSeconds, VenueServingContractFixture.currentUnixSeconds)
  }
}

/// Recorded responses for the production RegistryClient's two JSON-RPC calls.
/// The CBOR payload is the same registry context used by the signed venue
/// vector; it is wrapped in the ABI dynamic-bytes result expected by the
/// reader contract. The HTTP layer remains the production Darwin transport.
private final class RecordedVenueRegistryURLProtocol: URLProtocol {
  private static let contextABIHex =
    "0000000000000000000000000000000000000000000000000000000000000020" +
    "00000000000000000000000000000000000000000000000000000000000000b7" +
    "a3010102a40154111111111111111111111111111111111111111102542222222222222222222222222222222222222222035820cba59e50c7666ef2468a14f2e53f04decfd078933cd245a9a2d77532eb23b700041a6b49c26003a30101020103818601582000000000000000000000000000000000000000000000000000000000000000005820f1b4b54e6c911f1f02c1c9383c4914af56ffa3888ec28910f9f3204812276d7f1a6b49c6481a6b49dee31a6b49c3f0000000000000000000"

  override class func canInit(with request: URLRequest) -> Bool {
    request.url?.scheme == "https"
  }

  override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }

  override func startLoading() {
    let payload = String(data: Self.responseData(for: request.httpBody ?? Data()), encoding: .utf8)!
    let response = HTTPURLResponse(
      url: request.url!, statusCode: 200, httpVersion: nil,
      headerFields: ["Content-Type": "application/json"]
    )!
    client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
    client?.urlProtocol(self, didLoad: Data(payload.utf8))
    client?.urlProtocolDidFinishLoading(self)
  }

  override func stopLoading() {}

  static func responseData(for body: Data) -> Data {
    let text = String(data: body, encoding: .utf8) ?? ""
    if text.contains("eth_getBlockByNumber") {
      return Data("{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{\"number\":\"0x2a\",\"hash\":\"0x2222222222222222222222222222222222222222222222222222222222222222\"}}".utf8)
    }
    return Data("{\"jsonrpc\":\"2.0\",\"id\":2,\"result\":\"0x\(Self.contextABIHex)\"}".utf8)
  }
}
