// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:beid_app/data/models/sensing_record.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SensingRecordAdapter());
    registerAdapter(SensingStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SensingRecordAdapter());
    registerAdapter(SensingStatusAdapter());
  }
}
